### ISSUE TITLE
Understand why in some hardware configuration the SPH scenes explode

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto#130]
- [x] Add print debug for all constants / parameters that characterise a simulation and might lead to a different behaviour
- [x] Commit test to dump buffer 
- [x] Add test to dump all the buffers after N timestep for the liquid scene
- [ ] Compare the buffers of the liquid scene when running on Sergey's machine vs when running on Matteo's

**Comment by tarelli** [comment]
Deferring this to February after the looping simulation work is done

**Comment by tarelli** [comment]
@skhayrulin hey Sergey, any progress on this? Were the problems on your machine solved after we fixed eclipse? Do we need a meeting? :)

**Comment by skhayrulin** [comment]
Hi @tarelli,
Actually no I'm still have this problem with JavaCl and AMD drivers on my workstation, and I'm not sure that you can help me with this:), actually I even don't know who can:). But looks like on my home computer (It's ubuntu also) tests is passing  and no segfault is observable, but I have a problem with run gepetto there are some strange exceptions are appearing when I'm starting virgo, I think that you can help me with it. I mean run geppetto on my home station and in this case meeting will be very useful.

**Comment by tarelli** [comment]
@skhayrulin which one of these is your MacBook? I think it would be better to use that one to reproduce the problem.

**Comment by skhayrulin** [comment]
It's look like  the tests are passing on both my computers my Mac and on my PC with Ubuntu. But I can't run geppetto on virg I have a bunch of exceptions I'll send you a log

**Comment by tarelli** [comment]
Met with @skhayrulin, the error seems to be due to library not copied to repository usr, sergey will try to update this, the current strategy is still to compare output of the PC with Ubuntu where the scene doesn't explode with output of Mac where the scene explodes.

**Comment by tarelli** [comment]
Now focusing the effort on wrapping Sibernetic rather than on why the ported version behaves differently, see card https://github.com/openworm/org.geppetto.simulator.sph/issues/36.
