### ISSUE TITLE
Download links not working on live.geppetto.org with Firefox

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto#446]
Links on bottom right in experiment tab for download model/results (e.g. here: https://live.geppetto.org/geppetto?load_project_from_id=1) don't work, just show/hide the experiment details.

Firefox on Ubuntu

**Comment by tarelli** [comment]
@adrianq could you check if this happens in OSB live just to know if it's deployment related

**Comment by adrianq** [comment]
@tarelli This is the error in live.geppetto.org:
![screenshot from 2015-09-29 16 25 42](https://cloud.githubusercontent.com/assets/6850223/10168974/ebdedaa0-66c6-11e5-9043-8d58362c133d.png)

In OSB it is not working neither but it is a different error:
![screenshot from 2015-09-29 16 26 17](https://cloud.githubusercontent.com/assets/6850223/10168998/091d9214-66c7-11e5-882c-8891b6dc356d.png)

I haven't looked at it in details... just clicked the button and take a screenshot

**Comment by tarelli** [comment]
All seems fine locally, with or without DB, still confused about this

**Comment by adrianq** [comment]
In firefox with the persistence bundle, I am getting an error in [this line in the GEPPETTO.FE file](https://github.com/openworm/org.geppetto.frontend/blob/master/src/main/webapp/js/GEPPETTO.FE.js#L403)

cc @tarelli

**Comment by tarelli** [comment]
I think this was fixed, not happening in live anyway

**Comment by gidili** [comment]
I think I fixed this in a moment of madness

**Comment by adrianq** [comment]
@tarelli @gidili I think this is still happening in osb... I haven't updated the OSB version though. Will update this week and let you know...

**Comment by pgleeson** [comment]
Still happening in live OSB. Close when fixed there..?

**Comment by gidili** [comment]
If it's due to update of Geppetto on OSB we should close this and open a bug in the OSB repo?

**Comment by pgleeson** [comment]
Fine with me...

**Comment by adrianq** [comment]
Still failing in live.geppetto and OSB for firefox..

**Comment by tarelli** [comment]
![screen shot 2016-04-27 at 17 32 30](https://cloud.githubusercontent.com/assets/81127/14859888/0bc3b9b2-0c9e-11e6-905d-d2246c041ba9.png)
http://stackoverflow.com/questions/9813445/why-ff-says-that-window-event-is-undefined-call-function-with-added-event-list

**Comment by gidili** [comment]
Tried to fix this with @adrianq by using the event argument in the handler instead of window.event (should've been like that from the start), this takes care of the console error as expected but funny enough this uncovers yet another Firefox issue to do with downloading files via blob - all the examples I found using [the method we are using](https://github.com/openworm/org.geppetto.frontend/blob/development/src/main/webapp/js/GEPPETTO.Utility.js#L185) consistently work in chrome but not in firefox. 

Requires more investigation.

**Comment by tarelli** [comment]
@gidili @adrianq http://stackoverflow.com/questions/30694453/blob-createobjecturl-download-not-working-in-firefox-but-works-when-debugging have you guys seen this?

**Comment by gidili** [comment]
@tarelli yes - we are not removing the resource though. Regardless having a delay might be worth a shot.

**Comment by gidili** [comment]
@adrianq @tarelli can you guys test on dev branch? 

Working for me with these changes: 
- https://github.com/openworm/org.geppetto.frontend/commit/98fc7233ba79888663da3fdb1f474db2abe0c13c
- https://github.com/openworm/org.geppetto.frontend/commit/6f3c27e7a50ca202088f3b405392eec5c7b7d8a1

Might this be the end of the 'download not working' saga?

**Comment by adrianq** [comment]
It is working for me now. A little bit scared of this delay thing though. Not sure if it will work for any user.  [This lib](https://github.com/eligrey/FileSaver.js) can be another approach. Anyway, I think we can close it for now. Thanks @gidili !

**Comment by gidili** [comment]
@adrianq I think it's not too bad - the delay is only freeing up the handle to the file I think, in Firefox if happens too soon and something inside the 'click' handler goes haywire.

**Comment by tarelli** [comment]
Tested on firefox with geppetto 0.3.0 on live.geppetto.org. Working!
